# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce78d4af627c793787c012227b730ccd6422f5d6596066b978c01a558a2e850c8bd76a7981ff5757c109163b1c9f482b3efeaf780955328e18e4f63c2cb3abfb

test:
  secret_key_base: 55b78a17bdb2d76468aba581248fc76e595056b6552481ecb4aee414d4110f94a4a20d9c7d4bf5f618578c476aad27b27d5fa7c3ed5126b91b4285bfee89f57f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
